Recebimento de Grãos:
CREATE DATABASE recebimento_grão_db; /*Não tem necessidade de ter um banco na real.*/

CREATE TABLE rg_recebimento_graos (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	COD_ORIGEM INT NOT NULL, /*FK TB RGOrigem*/
	COD_PRODUTO INT NOT NULL COMMENT 'FK chamando o id da tabela RGOrigem', /* VERIFICAR/CRIAR TABELA COM OS TIPOS DE PRODUTOS*/
	COD_CLIENTE INT NOT NULL, /*FK TB PRODUTOR*/
	COD_CONTRATO INT NOT NULL, /*FK TB CONTRATO*/
	COD_CLASSIFICACAO INT NOT NULL, /*FK TB QUALIDADE GRAO*/
	COD_ARMAZENAMENTO INT NOT NULL, /* FK TB ARMAZENAMENTO FISICO*/
	COD_FRETE INT NOT NULL, /* FK TB FRETEIRO*/
	COD_FUNCIONARIO, INT NOT NULL /* Módulo RH <<<<< VERIFICAR >>>>>>> */ 
	FOREIGN KEY (COD_ORIGEM) REFERENCES rg_origem(ID), 
	FOREIGN KEY (COD_PRODUTO) REFERENCES rg_classificacao(ID), 
	FOREIGN KEY (COD_CLIENTE) REFERENCES rg_cliente(ID), 
	FOREIGN KEY (COD_CONTRATO) REFERENCES rg_contrato(ID), 
	FOREIGN KEY (COD_CLASSIFICACAO) REFERENCES rg_classificacao(ID), 
	FOREIGN KEY (COD_ARMAZENAMENTO) REFERENCES rg_armazenamento(ID), 
	FOREIGN KEY (COD_FRETE) REFERENCES rg_frete(ID), 
	FOREIGN KEY (COD_FUNCIONARIO) REFERENCES rh_funcionario(ID) /* VERIFICAR COM AS TABELAS DO <<<<< RH >>>> */ 
);

/*Tem mais informações sobre a Fazendo?*/
CREATE TABLE rg_origem (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FAZENDA_ORIGEM VARCHAR(100) NOT NULL, /* TESTE */
	COD_CLIENTE INT, /*FK TB PRODUTOR*/
	FOREIGN KEY (COD_CLIENTE) REFERENCES rg_cliente(ID) 
);

CREATE TABLE rg_cliente (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	ENDEREÇO VARCHAR(200) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	BLOCO_PRODUTOR VARCHAR(50),
);
	
CREATE TABLE rg_contrato (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TIPO_GRAO VARCHAR(20) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	SAFRA VARCHAR(5) NOT NULL      /*2022/2023, 2023/2024 ou 22/23, 23/24*/
);

CREATE TABLE rg_classificacao (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	COD_TIPO_GRAO INT,
	UMIDADE INT,
	PUREZA INT,
	ARDIDO INT,
	QUALIDADE_GRAO INT,
	COD_FUNCIONARIO INT,
	FOREIGN KEY (COD_TIPO_GRAO) REFERENCES rg_contrato(ID),
	FOREIGN KEY (COD_FUNCIONARIO) REFERENCES rh_funcionario(ID) 
);

CREATE TABLE rg_armazenamento (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	MOEGA INT,
	PESO_ENTRADA DECIMAL(10,2),
	PESO_SAIDA DECIMAL(10,2),
	TARA DECIMAL(10,2),
	COD_FRETE INT, /* FK  RGFreteiro */
	COD_CLIENTE INT, /* FK RGProdutor */
	COD_FAZENDA INT, /* FK TB RGOrigem */
	FOREIGN KEY (COD_FRETE) REFERENCES rg_frete(ID), 
	FOREIGN KEY (COD_CLIENTE) REFERENCES rg_origem(ID), 
	FOREIGN KEY (COD_FAZENDA) REFERENCES rg_frete(ID) 
);

CREATE TABLE rg_frete (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	PLACA_CAMINHAO VARCHAR(7) NOT NULL
);


/*
Origem - Origem do produto, fazendo de onde veio
Produto - Tipo do produto produzido
Produtor - Produtor que produziu o produto 
Contratos - Contrato de venda futura. Especifica produto, valor
Qualidade dos grãos - Tipificar os grãos para qualidade. Umidade, pureza, ardido. Quanto entrou e quanto saiu
Armazenamento Físico - Qual moega foi deixado e volume.
Freteiro - Responsável pelo frete do produto.
 */